In [ ]:
import pandas as pd

In [ ]:
headlines= pd.read_csv("merged_headlines_dataset_sorted.csv")

In [ ]:
headlines["published"].max()
headlines

,source,title,published
0,zdnet.com,US wiped some hard drives of Russia's 'troll f...,2019-03-01
1,nypost.com,Alleged home invader claims he was just chill...,2019-03-01
2,dailymail.co.uk,Minneapolis cop who killed Australian woman 'p...,2019-03-01
3,mobile.twitter.com,": Créelo o no, pero para el 2017, Nostradamus ...",2019-03-01
4,americanthinker.com,The Resistance: everything they accuse Trump o...,2019-03-01
...,...,...,...
22714,Google News,Starfish Necklace for Women Gold Star Swirl Pe...,2025-10-08
22715,Google News,"Black Pearl Necklace for Women, AAAA Quality G...",2025-10-08
22716,Google News,Round-Cut Moissanite Engagement Ring Set for W...,2025-10-08
22717,Google News,FindChic Handcuff Necklace Padlock Pendant Cus...,2025-10-08
22718,Google News,"Silver price charges to record high, tracking ...",2025-10-08

In [ ]:
!pip install yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.12)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.5.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (3.18.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.13.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.5)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.15.0)
Requirement already satisfied: cffi>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.0.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2025.10.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [ ]:
import yfinance as yf

gold = yf.download("GC=F", start="2019-03-01", end="2025-12-31", interval="1d")
print(len(gold))
gold.to_csv("daily_gold_prices.csv")

/tmp/ipython-input-2192772700.py:3: FutureWarning: YF.download() has changed argument auto_adjust default to True
  gold = yf.download("GC=F", start="2019-03-01", end="2025-12-31", interval="1d")
[*********************100%***********************]  1 of 1 completed

1666

In [ ]:
gold_dum = pd.read_csv("daily_gold_prices.csv")
gold

Price             Close         High          Low         Open  Volume
Ticker             GC=F         GC=F         GC=F         GC=F    GC=F
Date
2019-03-01  1296.400024  1312.199951  1288.900024  1312.199951     110
2019-03-04  1284.800049  1287.000000  1281.900024  1285.500000      28
2019-03-05  1282.000000  1287.000000  1282.000000  1287.000000     114
2019-03-06  1284.900024  1287.099976  1282.599976  1287.099976      14
2019-03-07  1283.800049  1284.599976  1281.000000  1281.000000      11
...                 ...          ...          ...          ...     ...
2025-10-06  3948.500000  3960.000000  3926.800049  3931.300049    1267
2025-10-07  3976.600098  3981.500000  3940.000000  3959.399902    2903
2025-10-08  4043.300049  4049.199951  3987.199951  3987.199951    2179
2025-10-09  3946.300049  4046.199951  3940.000000  4011.199951    3130
2025-10-10  4000.399902  4038.600098  3961.199951  3990.100098  352500

[1666 rows x 5 columns]

In [ ]:

col_names = ["Date", "Close", "High", "Low", "Open", "Volume"]

gold = pd.read_csv("daily_gold_prices.csv", skiprows=2, names=col_names)
gold = gold.drop(index=0)
gold

# Convert Date to datetime
#gold["Date"] = pd.to_datetime(gold["Date"])

            Date        Close         High          Low         Open    Volume
1     2019-03-01  1296.400024  1312.199951  1288.900024  1312.199951     110.0
2     2019-03-04  1284.800049  1287.000000  1281.900024  1285.500000      28.0
3     2019-03-05  1282.000000  1287.000000  1282.000000  1287.000000     114.0
4     2019-03-06  1284.900024  1287.099976  1282.599976  1287.099976      14.0
5     2019-03-07  1283.800049  1284.599976  1281.000000  1281.000000      11.0
...          ...          ...          ...          ...          ...       ...
1662  2025-10-06  3948.500000  3960.000000  3926.800049  3931.300049    1267.0
1663  2025-10-07  3976.600098  3981.500000  3940.000000  3959.399902    2903.0
1664  2025-10-08  4043.300049  4049.199951  3987.199951  3987.199951    2179.0
1665  2025-10-09  3946.300049  4046.199951  3940.000000  4011.199951    3130.0
1666  2025-10-10  4000.399902  4038.600098  3961.199951  3990.100098  352500.0

[1666 rows x 6 columns]

In [ ]:
headlines = headlines.sort_values(by='published', ascending=True)
headlines["published"]

0        2019-03-01
22       2019-03-01
23       2019-03-01
24       2019-03-01
25       2019-03-01
            ...
22343    2025-10-08
22344    2025-10-08
22345    2025-10-08
22339    2025-10-08
22718    2025-10-08
Name: published, Length: 22719, dtype: object

In [ ]:
!pip install transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.35.3)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.6.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.10.5)

In [ ]:
!pip install torch

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.8.0+cu126)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)

In [ ]:
!pip install huggingface_hub

Requirement already satisfied: huggingface_hub in /usr/local/lib/python3.12/dist-packages (0.35.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub) (1.1.10)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface_hub) (2025.10.5)

In [ ]:
import requests
import pandas as pd
import time
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.special import softmax
import numpy as np
import torch
import huggingface_hub

In [ ]:
model_name = "ProsusAI/finbert"
huggingface_hub.constants.HF_HUB_HTTP_TIMEOUT = 60  # extend timeout

In [ ]:
for attempt in range(5):
    try:
        print(f"\nAttempt {attempt+1}/5: Loading FinBERT model...")
        tokenizer = AutoTokenizer.from_pretrained(model_name)
        model = AutoModelForSequenceClassification.from_pretrained(model_name)
        print("✅ FinBERT loaded successfully!")
        break
    except Exception as e:
        print("⚠️ Error:", e)
        if attempt < 4:
            print("⏳ Retrying in 5 seconds...\n")
            time.sleep(5)
        else:
            raise e

Attempt 1/5: Loading FinBERT model...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

✅ FinBERT loaded successfully!

In [24]:
sentiments = []

for text in tqdm(headlines["title"].fillna(""), desc="Analyzing Sentiment"):
    try:
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
        outputs = model(**inputs)
        scores = softmax(outputs.logits.detach().numpy()[0])
        sentiments.append({
            "negative": float(scores[0]),
            "neutral": float(scores[1]),
            "positive": float(scores[2])
        })
    except Exception as e:
        sentiments.append({"negative": np.nan, "neutral": np.nan, "positive": np.nan})
        print("⚠️ Error on text:", text, "|", e)

sent_df = pd.DataFrame(sentiments)
headline_df = pd.concat([headlines.reset_index(drop=True), sent_df], axis=1)

Analyzing Sentiment: 100%|██████████| 22719/22719 [51:22<00:00,  7.37it/s]

In [30]:
import pandas as pd

# 1. Load gold prices CSV
col_names = ["Date", "Close", "High", "Low", "Open", "Volume"]
gold = pd.read_csv("daily_gold_prices.csv", skiprows=2, names=col_names)

# Drop any unnecessary first row if needed
gold = gold.drop(index=0)

# Convert Date to datetime (MM/DD/YYYY)
gold['Date'] = pd.to_datetime(gold['Date'], dayfirst=False, errors='coerce')



# Rename date column to match gold CSV
headline_df.rename(columns={"published": "Date"}, inplace=True)

# Convert Date to datetime (MM/DD/YYYY)
headline_df['Date'] = pd.to_datetime(headline_df['Date'], dayfirst=False, errors='coerce')

# 3. Merge datasets
merged = pd.merge(gold, headline_df, on='Date', how='outer')

# 4. Sort by Date ascending-
merged = merged.sort_values('Date').reset_index(drop=True)

In [29]:
merged.to_csv("gold_sentiment_merged.csv", index=False)

In [ ]:

!pip install pandas_datareader --quiet

import pandas_datareader.data as web
import pandas as pd
import datetime


start = datetime.datetime(2019, 3, 1)
end = datetime.datetime(2025, 10, 10)


interest_rate = web.DataReader("FEDFUNDS", "fred", start, end)


inflation = web.DataReader("FPCPITOTLZGUSA", "fred", start, end)


usd_index = web.DataReader("DTWEXBGS", "fred", start, end)


macro_df = pd.concat([interest_rate, inflation, usd_index], axis=1)
macro_df.columns = ["interest_rate", "inflation", "usd_index"]


macro_df = macro_df.reset_index()
macro_df.rename(columns={"index": "date"}, inplace=True)


macro_df.to_csv("macro_data.csv", index=False)

print("✅ macro_data.csv created successfully!")
print(macro_df.head())

✅ macro_data.csv created successfully!
        DATE  interest_rate  inflation  usd_index
0 2019-03-01           2.41        NaN   114.5350
1 2019-03-04            NaN        NaN   114.6903
2 2019-03-05            NaN        NaN   114.8019
3 2019-03-06            NaN        NaN   114.9697
4 2019-03-07            NaN        NaN   115.4905

In [ ]:
import pandas as pd


gold_df = pd.read_csv("gold_sentiment_merged.csv")
macro_df = pd.read_csv("macro_data.csv")


gold_df['Date'] = pd.to_datetime(gold_df['Date'])
macro_df.rename(columns={'DATE': 'Date'}, inplace=True)
macro_df['Date'] = pd.to_datetime(macro_df['Date'])


merged_df = pd.merge(gold_df, macro_df, on='Date', how='left')


merged_df[['interest_rate', 'inflation', 'usd_index']] = (
    merged_df[['interest_rate', 'inflation', 'usd_index']].ffill().bfill()
)


merged_df.to_csv("gold_macro_sentiment.csv", index=False)


print("Rows:", merged_df.shape[0])
print(merged_df.head())

✅ gold_macro_sentiment.csv created successfully!
Rows: 23693
        Date        Close         High          Low         Open  Volume  \
0 2019-03-01  1296.400024  1312.199951  1288.900024  1312.199951   110.0
1 2019-03-01  1296.400024  1312.199951  1288.900024  1312.199951   110.0
2 2019-03-01  1296.400024  1312.199951  1288.900024  1312.199951   110.0
3 2019-03-01  1296.400024  1312.199951  1288.900024  1312.199951   110.0
4 2019-03-01  1296.400024  1312.199951  1288.900024  1312.199951   110.0

               source                                              title  \
0           zdnet.com  US wiped some hard drives of Russia's 'troll f...
1          nypost.com  Alleged home invader claims he was just chill...
2     dailymail.co.uk  Minneapolis cop who killed Australian woman 'p...
3  mobile.twitter.com  : Créelo o no, pero para el 2017, Nostradamus ...
4         reuters.com  U.S. companies put record number of robots to ...

   negative   neutral  positive  interest_rate  inflation  usd_index
0  0.058440  0.285771  0.655790           2.41   4.697859    114.535
1  0.032158  0.730865  0.236977           2.41   4.697859    114.535
2  0.025439  0.837098  0.137463           2.41   4.697859    114.535
3  0.329040  0.034191  0.636770           2.41   4.697859    114.535
4  0.394123  0.043560  0.562318           2.41   4.697859    114.535